### ISSUE TITLE
mongo report gen error for a sample 

### ISSUE THREAD

**Issue by mallorybobalice** [doomedraven/cuckoo-modified#13]
for one the samples added multiple times I'm getting this.
dacbfcee81b78532831bf95bfd52dc91 (sublime editor windows setup)
https://www.hybrid-analysis.com/sample/9583c9ad1534d28bbe3d63f57bf0f85d5e5352daba3f5eac3f0ab7a490a7e309?environmentId=100

tried deleting tasks - not helping.

I don't know how i got it into this state, my other test samples i've submitted dozens of times without issues. (doesn't seem to be a duplicate submission issue)

````
2017-07-28 09:54:38,300 [modules.reporting.zcompression] DEBUG: zipping html or json reports
2017-07-28 09:54:38,582 [modules.reporting.zcompression] DEBUG: finished compressing report json
2017-07-28 09:54:38,743 [modules.reporting.zcompression] DEBUG: finished compressing report html
2017-07-28 09:54:38,744 [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "MongoDB"
2017-07-28 09:54:39,745 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "MongoDB":
Traceback (most recent call last):
  File "utils/../lib/cuckoo/core/plugins.py", line 631, in process
    current.run(self.results)
  File "utils/../modules/reporting/mongodb.py", line 184, in run
    child_key, csize = self.debug_dict_size(report[parent_key])[0]
  File "utils/../modules/reporting/mongodb.py", line 46, in debug_dict_size
    totals = dict((k, 0) for k in dct)
TypeError: unhashable type: 'dict'
````
any ideas :| ?

**Comment by mallorybobalice** [comment]
hmmm interesting i get it both on my new test box (ULTS 16.04.2  + latest source and py libs + from source libs) and the older source and libs prod one. 

on the test box
mongodb-org/xenial,now 3.2.15 
pymongo (3.4.0)

**Comment by mallorybobalice** [comment]
hmmm curious after reviewing historical processing logs this isn't that uncommon - say 1/250 samples.

**Comment by doomedraven** [comment]
you need debug that issue, i never had it generated by clear(without any personal changes)

**Comment by mallorybobalice** [comment]
=) any debug statemement tips cleverly enumerating the right attributes?

**Comment by doomedraven** [comment]
use pycharm/komodo ide/msvb any other tool which allow debugging. put bp on start in mongo reporting module, and execute till bp and than just step by step ;)

**Comment by mallorybobalice** [comment]
=) noob rtfm? Hmm alright. Always wanted to try a proper py ide and interactive debugger. 
Suppose I shall Google. 

People are always 'add a print or log.debug ' never saw anyone say bp xD but would save so much time

**Comment by doomedraven** [comment]
for my taste i prefer pycharm, community edition(free) is enough

**Comment by big-gunter** [comment]
Just as an FYI, this sample processes without issue if you use ElasticSearch in lieu of MongoDB. I realize it doesn't solve the issue, just found it interesting.

**Comment by doomedraven** [comment]
bcz ES doesn't care what to store, and mongo does
