### ISSUE TITLE
Issues with reporthtml.py on .net binaries

### ISSUE THREAD

**Issue by big-gunter** [doomedraven/cuckoo-modified#19]
Not sure how much of a true issue this is, however hoping it may have been seen before.

I have a binary which is compiled in .Net2.0. It will run on a VM in Cuckoo 2.0, however it bails in this version.

```
2017-10-13 18:09:08,114 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "ReportHTML":
Traceback (most recent call last):
  File "/home/exodus/doomedraven/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 631, in process
    current.run(self.results)
  File "/home/exodus/doomedraven/cuckoo-modified/utils/../modules/reporting/reporthtml.py", line 75, in run
    report.write(html)
  File "/usr/lib/python2.7/codecs.py", line 706, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
MemoryError
2017-10-13 18:13:40,501 [elasticsearch] WARNING: PUT http://127.0.0.1:9200/cuckoo_doom-2017-10-13/analysis/30 [status:N/A request:0.711s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 873, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
ProtocolError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2017-10-13 18:13:47,783 [elasticsearch] WARNING: PUT http://127.0.0.1:9200/cuckoo_doom-2017-10-13/analysis/30 [status:N/A request:6.788s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 873, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
ProtocolError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2017-10-13 18:13:49,662 [elasticsearch] WARNING: PUT http://127.0.0.1:9200/cuckoo_doom-2017-10-13/analysis/30 [status:N/A request:0.620s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 873, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
ProtocolError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2017-10-13 18:13:50,776 [elasticsearch] WARNING: PUT http://127.0.0.1:9200/cuckoo_doom-2017-10-13/analysis/30 [status:N/A request:0.585s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 873, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
ProtocolError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2017-10-13 18:13:51,173 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "ElasticsearchDB":
Traceback (most recent call last):
  File "/home/exodus/doomedraven/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 631, in process
    current.run(self.results)
  File "/home/exodus/doomedraven/cuckoo-modified/utils/../modules/reporting/elasticsearchdb.py", line 143, in run
    self.es.index(index=self.index_name, doc_type="analysis", id=results["info"]["id"], body=report)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 300, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 123, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(('Connection aborted.', error(104, 'Connection reset by peer'))) caused by: ProtocolError(('Connection aborted.', error(104, 'Connection reset by peer')))
2017-10-13 18:13:55,084 [root] INFO: Task #30: reports generation completed
2017-10-13 19:44:43,609 [root] INFO: Processing analysis data for Task #31
2017-10-13 19:50:53,014 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "JsonDump":
Traceback (most recent call last):
  File "/home/exodus/doomedraven/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 631, in process
    current.run(self.results)
  File "/home/exodus/doomedraven/cuckoo-modified/utils/../modules/reporting/jsondump.py", line 30, in run
    report.write(buf)
  File "/usr/lib/python2.7/codecs.py", line 706, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
MemoryError
2017-10-13 19:53:24,501 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "ReportHTML":
Traceback (most recent call last):
  File "/home/exodus/doomedraven/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 631, in process
    current.run(self.results)
  File "/home/exodus/doomedraven/cuckoo-modified/utils/../modules/reporting/reporthtml.py", line 65, in run
    html = tpl.render({"results": results, "summary_report" : False})
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 748, in handle_exception
    traceback = _make_traceback(exc_info, source_hint)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/debug.py", line 140, in make_traceback
    return translate_exception(exc_info, initial_skip)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/debug.py", line 193, in translate_exception
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 986, in render
    return concat(self.root_render_func(self.new_context(vars)))
MemoryError
2017-10-13 19:57:11,117 [elasticsearch] WARNING: PUT http://127.0.0.1:9200/cuckoo_doom-2017-10-13/analysis/31 [status:N/A request:1.675s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 873, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
ProtocolError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2017-10-13 19:57:13,818 [elasticsearch] WARNING: PUT http://127.0.0.1:9200/cuckoo_doom-2017-10-13/analysis/31 [status:N/A request:1.453s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 873, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
ProtocolError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2017-10-13 19:57:16,472 [elasticsearch] WARNING: PUT http://127.0.0.1:9200/cuckoo_doom-2017-10-13/analysis/31 [status:N/A request:1.701s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 873, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
ProtocolError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2017-10-13 19:57:25,849 [elasticsearch] WARNING: PUT http://127.0.0.1:9200/cuckoo_doom-2017-10-13/analysis/31 [status:N/A request:8.140s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 873, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
ProtocolError: ('Connection aborted.', error(104, 'Connection reset by peer'))
2017-10-13 19:57:27,711 [lib.cuckoo.core.plugins] ERROR: Failed to run the reporting module "ElasticsearchDB":
Traceback (most recent call last):
  File "/home/exodus/doomedraven/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 631, in process
    current.run(self.results)
  File "/home/exodus/doomedraven/cuckoo-modified/utils/../modules/reporting/elasticsearchdb.py", line 143, in run
    self.es.index(index=self.index_name, doc_type="analysis", id=results["info"]["id"], body=report)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 300, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 123, in perform_request
    raise ConnectionError('N/A', str(e), e)
ConnectionError: ConnectionError(('Connection aborted.', error(104, 'Connection reset by peer'))) caused by: ProtocolError(('Connection aborted.', error(104, 'Connection reset by peer')))
2017-10-13 19:57:31,017 [root] INFO: Task #31: reports generation completed
```
Obviously from that you can see I'm running ES instead of mongo on the backend, which I prefer. It appears that giant error is actually caused by the very first section, specifically the failure of the reporthtml.py in the core modules. I changed over to mongo for a test and it did function - albeit mongo borked at the data being >16mb.

The binary in question, as I said is .Net 2.0, googling found me an old issue from a year ago in the main cuckoo fork related to .Net binaries failing in analysis. Viewing the analyses folder I can see that report.html is missing. So this seems to fit my theory.

My question/bug is - any clues on why this would fail? It runs on manual launch and in Cuckoo 2.0 (using ES on the back end).

Would be interested to get opinions. Unfortunately I cannot share the binary as it's part of a current work project.

**Comment by big-gunter** [comment]
Issue I referred to in the main fork:

https://github.com/cuckoosandbox/cuckoo/issues/1151

**Comment by doomedraven** [comment]
ES is not supported in cuckoo-mod, so you MUST to use mongo here. but without any sample can't test nothing sorry

**Comment by big-gunter** [comment]
Out of interest, why is ES disliked? 

I moved a version to Mongo to test this and it was incredibly slow in the webui in browsing things like the behavioural analysis (had to click the link twice to bring the info back).

Mongo also seems to suffer from some odd issues e.g. I had a sample that errored out (data dropped - behavioural) as > 16mb (reporting the size as 5mb WTF). There seems to be some fundamental issues there. Not that ES isn’t without issues and is obviously more painful to maintain.

I am interested though - not trying to be difficult, genuinely curious.

Cheers 

BG



---

Jon Cooper
Melbourne, Victoria, Australia
Email: jon@ftml.net
Ph: 0422 013 330

**Comment by doomedraven** [comment]
dislike no, just no support, and i won't add it, as im not interested in that, so if someone interested, feel free to implement correct handling of ES, you can check ES problems in Brad's repo in issues ;)

hm no idea, mongo and webgui work fine for me, so maybe some mongo problems on your side? no idea, im using the latest mongo
