### ISSUE TITLE
Auxiliary.conf TOR Issue 

### ISSUE THREAD

**Issue by big-gunter** [doomedraven/cuckoo-modified#5]
When using the utils/manage.py runserver ip:port, the web server fails to run due not being able to locate a "[tor]" entry in auxilary.conf.

I've tested this using a full, new clone of the repo: running cuckoo.py, utils/rooter.py, utils/api.py, utils/process.py and web/manage.py.

Adding a [tor] entry to auxiliary.conf remedies the situation. The error reported when [tor] is not present is below:

```
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cuckoo/testing/cuckoo-modified/web/web/settings.py", line 35, in <module>
    tor_cfg = aux_cfg.tor
AttributeError: Config instance has no attribute 'tor'
```

**Comment by doomedraven** [comment]
should be fixed, see commit, let me knwo if that fixed, aux tor doesn't work anymore :P
